// ============================================================
// India Thematic Stock Knowledge Graph — Neo4j import script
// Themes: (A) Strait of Hormuz disruption  (B) India AI infrastructure
// Companion to india_theme_kg.md · compiled 2026-08-05
// Research scaffold only. Not investment advice.
// ============================================================

CREATE CONSTRAINT node_id IF NOT EXISTS FOR (n:Node) REQUIRE n.id IS UNIQUE;

// ------------------------------------------------------------
// 1. NODES
// ------------------------------------------------------------

UNWIND [
  // --- EVENTS / SHOCKS ---
  {id:'E_HORMUZ', type:'EVENT', label:'Strait of Hormuz disruption', note:'Closure declared 2 Mar 2026; partial reopening June 2026; status volatile'},
  {id:'E_AIBUILD', type:'EVENT', label:'India AI infrastructure capex cycle', note:'1.8 GW IT load 2026 -> 7-12 GW by 2030'},

  // --- GEOGRAPHY ---
  {id:'G_HORMUZ', type:'GEOGRAPHY', label:'Strait of Hormuz', note:'~20% of seaborne oil and LNG trade'},
  {id:'G_INDIA', type:'GEOGRAPHY', label:'India'},
  {id:'G_GCC', type:'GEOGRAPHY', label:'Gulf producers'},
  {id:'G_QATAR', type:'GEOGRAPHY', label:'Qatar'},
  {id:'G_OMAN', type:'GEOGRAPHY', label:'Oman', note:'largest single urea supplier to India'},
  {id:'G_RUSSIA', type:'GEOGRAPHY', label:'Russia', note:'substitute crude/LPG route'},
  {id:'G_CAPE', type:'GEOGRAPHY', label:'Cape of Good Hope reroute'},
  {id:'G_KERALA', type:'GEOGRAPHY', label:'Kerala', note:'Gulf remittance dependent'},
  {id:'G_ANDHRA', type:'GEOGRAPHY', label:'Andhra Pradesh'},
  {id:'G_GUJARAT', type:'GEOGRAPHY', label:'Gujarat'},

  // --- MACRO VARIABLES ---
  {id:'M_BRENT', type:'MACRO_VAR', label:'Brent crude price'},
  {id:'M_LNG_SPOT', type:'MACRO_VAR', label:'Spot LNG / JKM'},
  {id:'M_LPG_SAUDI_CP', type:'MACRO_VAR', label:'Saudi LPG contract price'},
  {id:'M_GRM', type:'MACRO_VAR', label:'Gross refining margin'},
  {id:'M_FREIGHT', type:'MACRO_VAR', label:'Tanker freight rates'},
  {id:'M_WARRISK', type:'MACRO_VAR', label:'Marine war-risk premium'},
  {id:'M_INR', type:'MACRO_VAR', label:'USD/INR'},
  {id:'M_CPI', type:'MACRO_VAR', label:'India CPI'},
  {id:'M_CAD', type:'MACRO_VAR', label:'Current account deficit'},
  {id:'M_REPO', type:'MACRO_VAR', label:'RBI policy rate'},
  {id:'M_UREA', type:'MACRO_VAR', label:'Global urea/DAP/sulphur price'},
  {id:'M_SUBSIDY', type:'MACRO_VAR', label:'Fertiliser and LPG subsidy bill'},

  // --- RAW MATERIALS ---
  {id:'RM_CRUDE', type:'RAW_MATERIAL', label:'Crude oil'},
  {id:'RM_LNG', type:'RAW_MATERIAL', label:'LNG'},
  {id:'RM_LPG', type:'RAW_MATERIAL', label:'LPG'},
  {id:'RM_NATGAS', type:'RAW_MATERIAL', label:'Natural gas'},
  {id:'RM_COAL', type:'RAW_MATERIAL', label:'Coal'},
  {id:'RM_NAPHTHA', type:'RAW_MATERIAL', label:'Naphtha'},
  {id:'RM_PROPYLENE', type:'RAW_MATERIAL', label:'Propylene'},
  {id:'RM_BENZENE', type:'RAW_MATERIAL', label:'Benzene'},
  {id:'RM_CBFS', type:'RAW_MATERIAL', label:'Carbon black feedstock'},
  {id:'RM_CARBONBLACK', type:'RAW_MATERIAL', label:'Carbon black'},
  {id:'RM_BASEOIL', type:'RAW_MATERIAL', label:'Base oil'},
  {id:'RM_SYNRUBBER', type:'RAW_MATERIAL', label:'Synthetic rubber'},
  {id:'RM_NATRUBBER', type:'RAW_MATERIAL', label:'Natural rubber'},
  {id:'RM_TIO2', type:'RAW_MATERIAL', label:'Titanium dioxide'},
  {id:'RM_SOLVENT', type:'RAW_MATERIAL', label:'Solvents'},
  {id:'RM_MONOMER', type:'RAW_MATERIAL', label:'Acrylic monomers'},
  {id:'RM_HDPE', type:'RAW_MATERIAL', label:'HDPE/LLDPE/PP resin'},
  {id:'RM_PVC', type:'RAW_MATERIAL', label:'PVC resin'},
  {id:'RM_PTA_MEG', type:'RAW_MATERIAL', label:'PTA/MEG'},
  {id:'RM_VAM', type:'RAW_MATERIAL', label:'Vinyl acetate monomer'},
  {id:'RM_LAB', type:'RAW_MATERIAL', label:'Linear alkyl benzene'},
  {id:'RM_PETCOKE', type:'RAW_MATERIAL', label:'Petroleum coke'},
  {id:'RM_LLP', type:'RAW_MATERIAL', label:'Liquid light paraffin'},
  {id:'RM_UREA', type:'RAW_MATERIAL', label:'Urea'},
  {id:'RM_SULPHUR', type:'RAW_MATERIAL', label:'Sulphur'},
  {id:'RM_AMMONIA', type:'RAW_MATERIAL', label:'Ammonia'},
  {id:'RM_PHOSACID', type:'RAW_MATERIAL', label:'Phosphoric acid'},
  {id:'RM_COPPER', type:'RAW_MATERIAL', label:'Copper'},
  {id:'RM_ALUMINIUM', type:'RAW_MATERIAL', label:'Aluminium'},
  {id:'RM_CRGO_STEEL', type:'RAW_MATERIAL', label:'CRGO electrical steel'},
  {id:'RM_REFRIGERANT', type:'RAW_MATERIAL', label:'Refrigerant / dielectric fluid'},
  {id:'RM_BATTERY', type:'RAW_MATERIAL', label:'Battery cells'},
  {id:'RM_GPU', type:'RAW_MATERIAL', label:'GPU / AI accelerator'},

  // --- PRODUCTS ---
  {id:'P_ATF', type:'PRODUCT', label:'Aviation turbine fuel'},
  {id:'P_DIESEL', type:'PRODUCT', label:'Diesel'},
  {id:'P_PETROL', type:'PRODUCT', label:'Petrol'},
  {id:'P_ETHANOL', type:'PRODUCT', label:'Ethanol'},
  {id:'P_PAINT', type:'PRODUCT', label:'Decorative paint'},
  {id:'P_TYRE', type:'PRODUCT', label:'Tyre'},
  {id:'P_PVC_PIPE', type:'PRODUCT', label:'PVC pipe'},
  {id:'P_CEMENT', type:'PRODUCT', label:'Cement'},
  {id:'P_UREA', type:'PRODUCT', label:'Urea fertiliser'},
  {id:'P_DAP', type:'PRODUCT', label:'DAP/NPK fertiliser'},
  {id:'P_DATACENTRE', type:'PRODUCT', label:'Data centre capacity (MW IT load)'},
  {id:'P_TRANSFORMER', type:'PRODUCT', label:'Power transformer'},
  {id:'P_SWITCHGEAR', type:'PRODUCT', label:'Switchgear / MV-LV distribution'},
  {id:'P_UPS', type:'PRODUCT', label:'UPS / DC power backup'},
  {id:'P_GENSET', type:'PRODUCT', label:'Diesel genset'},
  {id:'P_COOLING', type:'PRODUCT', label:'Precision cooling / CDU'},
  {id:'P_CHILLER', type:'PRODUCT', label:'Chiller'},
  {id:'P_POWERCABLE', type:'PRODUCT', label:'Power cable'},
  {id:'P_FIBRE', type:'PRODUCT', label:'Optical fibre / interconnect'},
  {id:'P_AISERVER', type:'PRODUCT', label:'AI server / GPU system'},
  {id:'P_FIRMPOWER', type:'PRODUCT', label:'Firm 24x7 power supply'},
  {id:'P_GRIDEQUIP', type:'PRODUCT', label:'Grid stability equipment (BESS/STATCOM)'},

  // --- CONSTRAINTS ---
  {id:'CN_POWER', type:'CONSTRAINT', label:'Power availability', note:'26.3 GW incremental DC load by FY32'},
  {id:'CN_TRANSMISSION', type:'CONSTRAINT', label:'Transmission evacuation capacity'},
  {id:'CN_GRIDSTAB', type:'CONSTRAINT', label:'Grid stability under volatile DC load ramps'},
  {id:'CN_WATER', type:'CONSTRAINT', label:'Water availability', note:'150bn -> 358bn litres/yr'},
  {id:'CN_GPU', type:'CONSTRAINT', label:'GPU supply', note:'36-52 week lead times'},
  {id:'CN_HBM', type:'CONSTRAINT', label:'HBM / advanced packaging'},
  {id:'CN_CRGO', type:'CONSTRAINT', label:'CRGO electrical steel imports'},
  {id:'CN_LAND', type:'CONSTRAINT', label:'Infra-ready land'},
  {id:'CN_SKILLS', type:'CONSTRAINT', label:'Liquid cooling / HV commissioning talent'},

  // --- TECHNOLOGY ---
  {id:'T_GENAI', type:'TECHNOLOGY', label:'Generative AI'},
  {id:'T_LIQUIDCOOL', type:'TECHNOLOGY', label:'Liquid cooling', note:'~75% of new pipeline'},
  {id:'T_HIGHDENSITY', type:'TECHNOLOGY', label:'High-density racks'},

  // --- POLICY ---
  {id:'POL_LPG_SUBSIDY', type:'POLICY', label:'Administered LPG pricing'},
  {id:'POL_EXCISE_CUT', type:'POLICY', label:'Fuel excise duty cuts (2026)'},
  {id:'POL_WINDFALL_TAX', type:'POLICY', label:'Windfall tax / SAED on upstream'},
  {id:'POL_APM_GAS', type:'POLICY', label:'APM gas price ceiling'},
  {id:'POL_GAS_CONTROL_ORDER', type:'POLICY', label:'Natural Gas Control Order (rationing)'},
  {id:'POL_NBS_SUBSIDY', type:'POLICY', label:'Nutrient Based Subsidy'},
  {id:'POL_DC_TAX', type:'POLICY', label:'21-year DC tax holiday to 2047'},
  {id:'POL_INDIAAI', type:'POLICY', label:'IndiaAI Mission'},
  {id:'POL_PLI_IT', type:'POLICY', label:'IT hardware PLI'},
  {id:'POL_SEMICON', type:'POLICY', label:'India Semiconductor Mission / OSAT'},

  // --- CUSTOMERS / INVESTORS ---
  {id:'CU_HYPERSCALER', type:'CUSTOMER', label:'Hyperscalers (Google, Meta, MSFT, AWS, OpenAI)'},
  {id:'CU_INDIAAI', type:'CUSTOMER', label:'IndiaAI sovereign compute'},
  {id:'CU_GCC_ENT', type:'CUSTOMER', label:'Global Capability Centres'},
  {id:'IN_BLACKSTONE', type:'INVESTOR', label:'Blackstone'},
  {id:'IN_BROOKFIELD', type:'INVESTOR', label:'Brookfield'},

  // --- ASSETS ---
  {id:'AS_JAMNAGAR_DC', type:'ASSET', label:'Reliance Jamnagar AI campus'},
  {id:'AS_VIZAG_DC', type:'ASSET', label:'Google Visakhapatnam AI hub'},

  // --- PRIVATE / UNLISTED ---
  {id:'PC_ADANICONNEX', type:'PRIVATE_CO', label:'AdaniConneX'},
  {id:'PC_CTRLS', type:'PRIVATE_CO', label:'CtrlS Datacenters'},
  {id:'PC_YOTTA', type:'PRIVATE_CO', label:'Yotta'},
  {id:'PC_NXTRA', type:'PRIVATE_CO', label:'Nxtra by Airtel'},
  {id:'PC_NEYSA', type:'PRIVATE_CO', label:'Neysa'},
  {id:'PC_AIRTRUNK', type:'PRIVATE_CO', label:'AirTrunk'},
  {id:'PC_EQUINIX', type:'PRIVATE_CO', label:'Equinix India'},
  {id:'PC_NVIDIA', type:'PRIVATE_CO', label:'NVIDIA'},
  {id:'PC_NAYARA', type:'PRIVATE_CO', label:'Nayara Energy'},

  // --- SECTORS ---
  {id:'S_OILGAS', type:'SECTOR', label:'Oil & Gas'},
  {id:'S_SHIPPING', type:'SECTOR', label:'Shipping & Logistics'},
  {id:'S_AVIATION', type:'SECTOR', label:'Aviation'},
  {id:'S_CHEMICALS', type:'SECTOR', label:'Chemicals'},
  {id:'S_FERTILISER', type:'SECTOR', label:'Fertilisers & Agri-inputs'},
  {id:'S_PAINTS', type:'SECTOR', label:'Paints & Adhesives'},
  {id:'S_TYRES', type:'SECTOR', label:'Tyres'},
  {id:'S_CAPGOODS', type:'SECTOR', label:'Capital Goods & Electricals'},
  {id:'S_COOLING', type:'SECTOR', label:'HVAC & Thermal Management'},
  {id:'S_CABLES', type:'SECTOR', label:'Cables & Wires'},
  {id:'S_EMS', type:'SECTOR', label:'EMS & Compute Hardware'},
  {id:'S_POWER', type:'SECTOR', label:'Power & Utilities'},
  {id:'S_TELECOM', type:'SECTOR', label:'Telecom & Connectivity'},
  {id:'S_REALESTATE', type:'SECTOR', label:'Real Estate & REITs'},
  {id:'S_BFSI', type:'SECTOR', label:'Banks & NBFCs'},
  {id:'S_IT', type:'SECTOR', label:'IT Services'},
  {id:'S_DEFENCE', type:'SECTOR', label:'Defence'},
  {id:'S_METALS', type:'SECTOR', label:'Metals & Mining'},
  {id:'S_CEMENT', type:'SECTOR', label:'Cement'},
  {id:'S_AUTO', type:'SECTOR', label:'Automobiles'},
  {id:'S_FMCG', type:'SECTOR', label:'FMCG'},
  {id:'S_EPC', type:'SECTOR', label:'EPC & Infrastructure'},
  {id:'S_WATER', type:'SECTOR', label:'Water & Environment'}
] AS n
MERGE (x:Node {id:n.id})
SET x.type = n.type, x.label = n.label, x.note = n.note;

// ------------------------------------------------------------
// 2. COMPANIES  (sector, ticker, themes)
// ------------------------------------------------------------

UNWIND [
  // Theme A - oil & gas
  {id:'C_ONGC', label:'Oil & Natural Gas Corp', ticker:'ONGC', sector:'S_OILGAS', themes:['A']},
  {id:'C_OIL', label:'Oil India', ticker:'OIL', sector:'S_OILGAS', themes:['A']},
  {id:'C_GAIL', label:'GAIL (India)', ticker:'GAIL', sector:'S_OILGAS', themes:['A']},
  {id:'C_IOC', label:'Indian Oil', ticker:'IOC', sector:'S_OILGAS', themes:['A']},
  {id:'C_BPCL', label:'Bharat Petroleum', ticker:'BPCL', sector:'S_OILGAS', themes:['A']},
  {id:'C_HPCL', label:'Hindustan Petroleum', ticker:'HINDPETRO', sector:'S_OILGAS', themes:['A']},
  {id:'C_MRPL', label:'Mangalore Refinery', ticker:'MRPL', sector:'S_OILGAS', themes:['A']},
  {id:'C_CPCL', label:'Chennai Petroleum', ticker:'CHENNPETRO', sector:'S_OILGAS', themes:['A']},
  {id:'C_RIL', label:'Reliance Industries', ticker:'RELIANCE', sector:'S_OILGAS', themes:['A','B']},
  {id:'C_PETRONET', label:'Petronet LNG', ticker:'PETRONET', sector:'S_OILGAS', themes:['A']},
  {id:'C_GSPL', label:'Gujarat State Petronet', ticker:'GSPL', sector:'S_OILGAS', themes:['A']},
  {id:'C_IGL', label:'Indraprastha Gas', ticker:'IGL', sector:'S_OILGAS', themes:['A']},
  {id:'C_MGL', label:'Mahanagar Gas', ticker:'MGL', sector:'S_OILGAS', themes:['A']},
  {id:'C_GUJGAS', label:'Gujarat Gas', ticker:'GUJGASLTD', sector:'S_OILGAS', themes:['A']},
  {id:'C_ATGL', label:'Adani Total Gas', ticker:'ATGL', sector:'S_OILGAS', themes:['A']},
  {id:'C_SELAN', label:'Selan Exploration', ticker:'SELAN', sector:'S_OILGAS', themes:['A']},

  // Theme A - shipping, ports, aviation
  {id:'C_GESHIP', label:'Great Eastern Shipping', ticker:'GESHIP', sector:'S_SHIPPING', themes:['A']},
  {id:'C_SCI', label:'Shipping Corporation of India', ticker:'SCI', sector:'S_SHIPPING', themes:['A']},
  {id:'C_SEAMEC', label:'Seamec', ticker:'SEAMECLTD', sector:'S_SHIPPING', themes:['A']},
  {id:'C_ADANIPORTS', label:'Adani Ports & SEZ', ticker:'ADANIPORTS', sector:'S_SHIPPING', themes:['A','B']},
  {id:'C_JSWINFRA', label:'JSW Infrastructure', ticker:'JSWINFRA', sector:'S_SHIPPING', themes:['A']},
  {id:'C_CONCOR', label:'Container Corp of India', ticker:'CONCOR', sector:'S_SHIPPING', themes:['A']},
  {id:'C_ALLCARGO', label:'Allcargo Logistics', ticker:'ALLCARGO', sector:'S_SHIPPING', themes:['A']},
  {id:'C_TCI', label:'Transport Corp of India', ticker:'TCI', sector:'S_SHIPPING', themes:['A']},
  {id:'C_INDIGO', label:'InterGlobe Aviation', ticker:'INDIGO', sector:'S_AVIATION', themes:['A','B']},
  {id:'C_SPICEJET', label:'SpiceJet', ticker:'SPICEJET', sector:'S_AVIATION', themes:['A']},

  // Theme A - paints, tyres, plastics, chemicals
  {id:'C_ASIANPAINT', label:'Asian Paints', ticker:'ASIANPAINT', sector:'S_PAINTS', themes:['A']},
  {id:'C_BERGER', label:'Berger Paints', ticker:'BERGEPAINT', sector:'S_PAINTS', themes:['A']},
  {id:'C_KANSAI', label:'Kansai Nerolac', ticker:'KANSAINER', sector:'S_PAINTS', themes:['A']},
  {id:'C_INDIGOPNT', label:'Indigo Paints', ticker:'INDIGOPNTS', sector:'S_PAINTS', themes:['A']},
  {id:'C_AKZO', label:'Akzo Nobel India', ticker:'AKZOINDIA', sector:'S_PAINTS', themes:['A']},
  {id:'C_PIDILITE', label:'Pidilite Industries', ticker:'PIDILITIND', sector:'S_PAINTS', themes:['A']},
  {id:'C_GRASIM', label:'Grasim Industries', ticker:'GRASIM', sector:'S_PAINTS', themes:['A']},
  {id:'C_MRF', label:'MRF', ticker:'MRF', sector:'S_TYRES', themes:['A']},
  {id:'C_APOLLOTYRE', label:'Apollo Tyres', ticker:'APOLLOTYRE', sector:'S_TYRES', themes:['A']},
  {id:'C_CEAT', label:'CEAT', ticker:'CEATLTD', sector:'S_TYRES', themes:['A']},
  {id:'C_JKTYRE', label:'JK Tyre', ticker:'JKTYRE', sector:'S_TYRES', themes:['A']},
  {id:'C_BALKRISHNA', label:'Balkrishna Industries', ticker:'BALKRISIND', sector:'S_TYRES', themes:['A']},
  {id:'C_PCBL', label:'PCBL', ticker:'PCBL', sector:'S_CHEMICALS', themes:['A']},
  {id:'C_HIMADRI', label:'Himadri Speciality Chemical', ticker:'HSCL', sector:'S_CHEMICALS', themes:['A']},
  {id:'C_SUPREME', label:'Supreme Industries', ticker:'SUPREMEIND', sector:'S_CHEMICALS', themes:['A']},
  {id:'C_ASTRAL', label:'Astral', ticker:'ASTRAL', sector:'S_CHEMICALS', themes:['A']},
  {id:'C_FINOLEXIND', label:'Finolex Industries', ticker:'FINPIPE', sector:'S_CHEMICALS', themes:['A']},
  {id:'C_PRINCEPIPE', label:'Prince Pipes', ticker:'PRINCEPIPE', sector:'S_CHEMICALS', themes:['A']},
  {id:'C_POLYPLEX', label:'Polyplex', ticker:'POLYPLEX', sector:'S_CHEMICALS', themes:['A']},
  {id:'C_COSMO', label:'Cosmo First', ticker:'COSMOFIRST', sector:'S_CHEMICALS', themes:['A']},
  {id:'C_UFLEX', label:'UFlex', ticker:'UFLEX', sector:'S_CHEMICALS', themes:['A']},
  {id:'C_EPL', label:'EPL Ltd', ticker:'EPL', sector:'S_CHEMICALS', themes:['A']},
  {id:'C_TIMETECHNO', label:'Time Technoplast', ticker:'TIMETECHNO', sector:'S_CHEMICALS', themes:['A']},
  {id:'C_SRF', label:'SRF', ticker:'SRF', sector:'S_CHEMICALS', themes:['A','B']},
  {id:'C_NAVINFLUOR', label:'Navin Fluorine', ticker:'NAVINFLUOR', sector:'S_CHEMICALS', themes:['A','B']},
  {id:'C_GFL', label:'Gujarat Fluorochemicals', ticker:'FLUOROCHEM', sector:'S_CHEMICALS', themes:['A','B']},
  {id:'C_AARTIIND', label:'Aarti Industries', ticker:'AARTIIND', sector:'S_CHEMICALS', themes:['A']},
  {id:'C_DEEPAKNTR', label:'Deepak Nitrite', ticker:'DEEPAKNTR', sector:'S_CHEMICALS', themes:['A']},
  {id:'C_ATUL', label:'Atul', ticker:'ATUL', sector:'S_CHEMICALS', themes:['A']},
  {id:'C_VINATI', label:'Vinati Organics', ticker:'VINATIORGA', sector:'S_CHEMICALS', themes:['A']},
  {id:'C_TATACHEM', label:'Tata Chemicals', ticker:'TATACHEM', sector:'S_CHEMICALS', themes:['A']},
  {id:'C_GHCL', label:'GHCL', ticker:'GHCL', sector:'S_CHEMICALS', themes:['A']},
  {id:'C_ALKYLAMINE', label:'Alkyl Amines', ticker:'ALKYLAMINE', sector:'S_CHEMICALS', themes:['A']},

  // Theme A - fertilisers
  {id:'C_CHAMBAL', label:'Chambal Fertilisers', ticker:'CHAMBLFERT', sector:'S_FERTILISER', themes:['A']},
  {id:'C_COROMANDEL', label:'Coromandel International', ticker:'COROMANDEL', sector:'S_FERTILISER', themes:['A']},
  {id:'C_GNFC', label:'GNFC', ticker:'GNFC', sector:'S_FERTILISER', themes:['A']},
  {id:'C_GSFC', label:'GSFC', ticker:'GSFC', sector:'S_FERTILISER', themes:['A']},
  {id:'C_RCF', label:'Rashtriya Chemicals & Fertilizers', ticker:'RCF', sector:'S_FERTILISER', themes:['A']},
  {id:'C_NFL', label:'National Fertilizers', ticker:'NFL', sector:'S_FERTILISER', themes:['A']},
  {id:'C_DEEPAKFERT', label:'Deepak Fertilisers', ticker:'DEEPAKFERT', sector:'S_FERTILISER', themes:['A']},
  {id:'C_PARADEEP', label:'Paradeep Phosphates', ticker:'PARADEEP', sector:'S_FERTILISER', themes:['A']},
  {id:'C_FACT', label:'FACT', ticker:'FACT', sector:'S_FERTILISER', themes:['A']},
  {id:'C_UPL', label:'UPL', ticker:'UPL', sector:'S_FERTILISER', themes:['A']},
  {id:'C_PIIND', label:'PI Industries', ticker:'PIIND', sector:'S_FERTILISER', themes:['A']},
  {id:'C_RALLIS', label:'Rallis India', ticker:'RALLIS', sector:'S_FERTILISER', themes:['A']},

  // Theme A - substitution beneficiaries
  {id:'C_COALINDIA', label:'Coal India', ticker:'COALINDIA', sector:'S_POWER', themes:['A','B']},
  {id:'C_BALRAMPUR', label:'Balrampur Chini', ticker:'BALRAMCHIN', sector:'S_FMCG', themes:['A']},
  {id:'C_TRIVENI', label:'Triveni Engineering', ticker:'TRIVENI', sector:'S_FMCG', themes:['A']},
  {id:'C_SHREERENUKA', label:'Shree Renuka Sugars', ticker:'RENUKA', sector:'S_FMCG', themes:['A']},
  {id:'C_PRAJ', label:'Praj Industries', ticker:'PRAJIND', sector:'S_CAPGOODS', themes:['A']},

  // Theme A - consumer, cement, metals, autos
  {id:'C_HUL', label:'Hindustan Unilever', ticker:'HINDUNILVR', sector:'S_FMCG', themes:['A']},
  {id:'C_MARICO', label:'Marico', ticker:'MARICO', sector:'S_FMCG', themes:['A']},
  {id:'C_GODREJCP', label:'Godrej Consumer', ticker:'GODREJCP', sector:'S_FMCG', themes:['A']},
  {id:'C_DABUR', label:'Dabur India', ticker:'DABUR', sector:'S_FMCG', themes:['A']},
  {id:'C_JYOTHYLAB', label:'Jyothy Labs', ticker:'JYOTHYLAB', sector:'S_FMCG', themes:['A']},
  {id:'C_CASTROL', label:'Castrol India', ticker:'CASTROLIND', sector:'S_OILGAS', themes:['A']},
  {id:'C_GULFOIL', label:'Gulf Oil Lubricants', ticker:'GULFOILLUB', sector:'S_OILGAS', themes:['A']},
  {id:'C_ULTRACEMCO', label:'UltraTech Cement', ticker:'ULTRACEMCO', sector:'S_CEMENT', themes:['A','B']},
  {id:'C_AMBUJA', label:'Ambuja Cements', ticker:'AMBUJACEM', sector:'S_CEMENT', themes:['A','B']},
  {id:'C_SHREECEM', label:'Shree Cement', ticker:'SHREECEM', sector:'S_CEMENT', themes:['A']},
  {id:'C_DALMIA', label:'Dalmia Bharat', ticker:'DALBHARAT', sector:'S_CEMENT', themes:['A']},
  {id:'C_HINDALCO', label:'Hindalco', ticker:'HINDALCO', sector:'S_METALS', themes:['A','B']},
  {id:'C_NALCO', label:'National Aluminium', ticker:'NATIONALUM', sector:'S_METALS', themes:['A','B']},
  {id:'C_VEDL', label:'Vedanta', ticker:'VEDL', sector:'S_METALS', themes:['A','B']},
  {id:'C_JSWSTEEL', label:'JSW Steel', ticker:'JSWSTEEL', sector:'S_METALS', themes:['A','B']},
  {id:'C_TATASTEEL', label:'Tata Steel', ticker:'TATASTEEL', sector:'S_METALS', themes:['A','B']},
  {id:'C_HINDCOPPER', label:'Hindustan Copper', ticker:'HINDCOPPER', sector:'S_METALS', themes:['B']},
  {id:'C_MARUTI', label:'Maruti Suzuki', ticker:'MARUTI', sector:'S_AUTO', themes:['A']},
  {id:'C_HEROMOTOCO', label:'Hero MotoCorp', ticker:'HEROMOTOCO', sector:'S_AUTO', themes:['A']},
  {id:'C_BAJAJAUTO', label:'Bajaj Auto', ticker:'BAJAJ-AUTO', sector:'S_AUTO', themes:['A']},
  {id:'C_TVSMOTOR', label:'TVS Motor', ticker:'TVSMOTOR', sector:'S_AUTO', themes:['A']},
  {id:'C_TATAMOTORS', label:'Tata Motors', ticker:'TATAMOTORS', sector:'S_AUTO', themes:['A']},
  {id:'C_MM', label:'Mahindra & Mahindra', ticker:'M&M', sector:'S_AUTO', themes:['A']},
  {id:'C_OLECTRA', label:'Olectra Greentech', ticker:'OLECTRA', sector:'S_AUTO', themes:['A']},

  // Theme A - financials, IT, defence, insurance
  {id:'C_BAJFINANCE', label:'Bajaj Finance', ticker:'BAJFINANCE', sector:'S_BFSI', themes:['A']},
  {id:'C_CHOLAFIN', label:'Cholamandalam Investment', ticker:'CHOLAFIN', sector:'S_BFSI', themes:['A']},
  {id:'C_SHRIRAMFIN', label:'Shriram Finance', ticker:'SHRIRAMFIN', sector:'S_BFSI', themes:['A']},
  {id:'C_MUTHOOT', label:'Muthoot Finance', ticker:'MUTHOOTFIN', sector:'S_BFSI', themes:['A']},
  {id:'C_MANAPPURAM', label:'Manappuram Finance', ticker:'MANAPPURAM', sector:'S_BFSI', themes:['A']},
  {id:'C_HDFCBANK', label:'HDFC Bank', ticker:'HDFCBANK', sector:'S_BFSI', themes:['A']},
  {id:'C_SBIN', label:'State Bank of India', ticker:'SBIN', sector:'S_BFSI', themes:['A','B']},
  {id:'C_AUBANK', label:'AU Small Finance Bank', ticker:'AUBANK', sector:'S_BFSI', themes:['A']},
  {id:'C_FEDERALBNK', label:'Federal Bank', ticker:'FEDERALBNK', sector:'S_BFSI', themes:['A']},
  {id:'C_SIB', label:'South Indian Bank', ticker:'SOUTHBANK', sector:'S_BFSI', themes:['A']},
  {id:'C_CSBBANK', label:'CSB Bank', ticker:'CSBBANK', sector:'S_BFSI', themes:['A']},
  {id:'C_DHANBANK', label:'Dhanlaxmi Bank', ticker:'DHANBANK', sector:'S_BFSI', themes:['A']},
  {id:'C_GICRE', label:'GIC Re', ticker:'GICRE', sector:'S_BFSI', themes:['A']},
  {id:'C_NIACL', label:'New India Assurance', ticker:'NIACL', sector:'S_BFSI', themes:['A']},
  {id:'C_ICICIGI', label:'ICICI Lombard', ticker:'ICICIGI', sector:'S_BFSI', themes:['A']},
  {id:'C_TCS', label:'Tata Consultancy Services', ticker:'TCS', sector:'S_IT', themes:['A','B']},
  {id:'C_INFY', label:'Infosys', ticker:'INFY', sector:'S_IT', themes:['A','B']},
  {id:'C_HCLTECH', label:'HCL Technologies', ticker:'HCLTECH', sector:'S_IT', themes:['A','B']},
  {id:'C_WIPRO', label:'Wipro', ticker:'WIPRO', sector:'S_IT', themes:['A','B']},
  {id:'C_LTIM', label:'LTIMindtree', ticker:'LTIM', sector:'S_IT', themes:['A','B']},
  {id:'C_PERSISTENT', label:'Persistent Systems', ticker:'PERSISTENT', sector:'S_IT', themes:['B']},
  {id:'C_COFORGE', label:'Coforge', ticker:'COFORGE', sector:'S_IT', themes:['B']},
  {id:'C_QUICKHEAL', label:'Quick Heal Technologies', ticker:'QUICKHEAL', sector:'S_IT', themes:['B']},
  {id:'C_SUNPHARMA', label:'Sun Pharmaceutical', ticker:'SUNPHARMA', sector:'S_FMCG', themes:['A']},
  {id:'C_DRREDDY', label:"Dr Reddy's Laboratories", ticker:'DRREDDY', sector:'S_FMCG', themes:['A']},
  {id:'C_CIPLA', label:'Cipla', ticker:'CIPLA', sector:'S_FMCG', themes:['A']},
  {id:'C_DIVIS', label:"Divi's Laboratories", ticker:'DIVISLAB', sector:'S_FMCG', themes:['A']},
  {id:'C_HAL', label:'Hindustan Aeronautics', ticker:'HAL', sector:'S_DEFENCE', themes:['A']},
  {id:'C_BEL', label:'Bharat Electronics', ticker:'BEL', sector:'S_DEFENCE', themes:['A']},
  {id:'C_BDL', label:'Bharat Dynamics', ticker:'BDL', sector:'S_DEFENCE', themes:['A']},
  {id:'C_SOLARINDS', label:'Solar Industries', ticker:'SOLARINDS', sector:'S_DEFENCE', themes:['A']},
  {id:'C_COCHINSHIP', label:'Cochin Shipyard', ticker:'COCHINSHIP', sector:'S_DEFENCE', themes:['A']},
  {id:'C_MAZDOCK', label:'Mazagon Dock', ticker:'MAZDOCK', sector:'S_DEFENCE', themes:['A']},
  {id:'C_GRSE', label:'Garden Reach Shipbuilders', ticker:'GRSE', sector:'S_DEFENCE', themes:['A']},
  {id:'C_DATAPATTNS', label:'Data Patterns', ticker:'DATAPATTNS', sector:'S_DEFENCE', themes:['A']},
  {id:'C_ASTRAMICRO', label:'Astra Microwave', ticker:'ASTRAMICRO', sector:'S_DEFENCE', themes:['A']},

  // Theme B - operators & developers
  {id:'C_ADANIENT', label:'Adani Enterprises', ticker:'ADANIENT', sector:'S_POWER', themes:['A','B']},
  {id:'C_BHARTIARTL', label:'Bharti Airtel', ticker:'BHARTIARTL', sector:'S_TELECOM', themes:['B']},
  {id:'C_TATACOMM', label:'Tata Communications', ticker:'TATACOMM', sector:'S_TELECOM', themes:['B']},
  {id:'C_ANANTRAJ', label:'Anant Raj', ticker:'ANANTRAJ', sector:'S_REALESTATE', themes:['B']},
  {id:'C_LODHA', label:'Macrotech Developers', ticker:'LODHA', sector:'S_REALESTATE', themes:['B']},
  {id:'C_RAILTEL', label:'RailTel Corporation', ticker:'RAILTEL', sector:'S_TELECOM', themes:['B']},
  {id:'C_DLF', label:'DLF', ticker:'DLF', sector:'S_REALESTATE', themes:['B']},
  {id:'C_EMBASSY', label:'Embassy Office Parks REIT', ticker:'EMBASSY', sector:'S_REALESTATE', themes:['B']},
  {id:'C_MINDSPACE', label:'Mindspace Business Parks REIT', ticker:'MINDSPACE', sector:'S_REALESTATE', themes:['B']},
  {id:'C_BRIGADE', label:'Brigade Enterprises', ticker:'BRIGADE', sector:'S_REALESTATE', themes:['B']},

  // Theme B - electrical backbone
  {id:'C_ABB', label:'ABB India', ticker:'ABB', sector:'S_CAPGOODS', themes:['B']},
  {id:'C_SIEMENS', label:'Siemens India', ticker:'SIEMENS', sector:'S_CAPGOODS', themes:['B']},
  {id:'C_SIEMENSENER', label:'Siemens Energy India', ticker:'SIEMENSENER', sector:'S_CAPGOODS', themes:['B']},
  {id:'C_HITACHIENER', label:'Hitachi Energy India', ticker:'POWERINDIA', sector:'S_CAPGOODS', themes:['B']},
  {id:'C_GEVERNOVA', label:'GE Vernova T&D India', ticker:'GVT&D', sector:'S_CAPGOODS', themes:['B']},
  {id:'C_SCHNEIDER', label:'Schneider Electric Infrastructure', ticker:'SCHNEIDER', sector:'S_CAPGOODS', themes:['B']},
  {id:'C_CGPOWER', label:'CG Power & Industrial Solutions', ticker:'CGPOWER', sector:'S_CAPGOODS', themes:['B']},
  {id:'C_VOLTAMP', label:'Voltamp Transformers', ticker:'VOLTAMP', sector:'S_CAPGOODS', themes:['B']},
  {id:'C_TRIL', label:'Transformers & Rectifiers India', ticker:'TARIL', sector:'S_CAPGOODS', themes:['B']},
  {id:'C_SHILCHAR', label:'Shilchar Technologies', ticker:'SHILCTECH', sector:'S_CAPGOODS', themes:['B']},
  {id:'C_CUMMINSIND', label:'Cummins India', ticker:'CUMMINSIND', sector:'S_CAPGOODS', themes:['A','B']},
  {id:'C_KOEL', label:'Kirloskar Oil Engines', ticker:'KIRLOSENG', sector:'S_CAPGOODS', themes:['A','B']},
  {id:'C_HBLENGINE', label:'HBL Engineering', ticker:'HBLENGINE', sector:'S_CAPGOODS', themes:['B']},
  {id:'C_APARINDS', label:'Apar Industries', ticker:'APARINDS', sector:'S_CAPGOODS', themes:['A','B']},
  {id:'C_HPL', label:'HPL Electric & Power', ticker:'HPL', sector:'S_CAPGOODS', themes:['B']},
  {id:'C_BHEL', label:'BHEL', ticker:'BHEL', sector:'S_CAPGOODS', themes:['B']},
  {id:'C_THERMAX', label:'Thermax', ticker:'THERMAX', sector:'S_CAPGOODS', themes:['A','B']},

  // Theme B - cooling
  {id:'C_BLUESTARCO', label:'Blue Star', ticker:'BLUESTARCO', sector:'S_COOLING', themes:['B']},
  {id:'C_VOLTAS', label:'Voltas', ticker:'VOLTAS', sector:'S_COOLING', themes:['A','B']},
  {id:'C_KRN', label:'KRN Heat Exchanger', ticker:'KRN', sector:'S_COOLING', themes:['B'], purity:'high'},
  {id:'C_AMBER', label:'Amber Enterprises', ticker:'AMBER', sector:'S_COOLING', themes:['B']},
  {id:'C_JCHAC', label:'Johnson Controls-Hitachi AC India', ticker:'JCHAC', sector:'S_COOLING', themes:['B']},
  {id:'C_EPACK', label:'EPACK Durable', ticker:'EPACK', sector:'S_COOLING', themes:['B']},

  // Theme B - compute, EMS, semis
  {id:'C_NETWEB', label:'Netweb Technologies', ticker:'NETWEB', sector:'S_EMS', themes:['B'], purity:'high'},
  {id:'C_DIXON', label:'Dixon Technologies', ticker:'DIXON', sector:'S_EMS', themes:['B']},
  {id:'C_KAYNES', label:'Kaynes Technology', ticker:'KAYNES', sector:'S_EMS', themes:['B']},
  {id:'C_SYRMA', label:'Syrma SGS Technology', ticker:'SYRMA', sector:'S_EMS', themes:['B']},
  {id:'C_CYIENTDLM', label:'Cyient DLM', ticker:'CYIENTDLM', sector:'S_EMS', themes:['B']},
  {id:'C_TATAELXSI', label:'Tata Elxsi', ticker:'TATAELXSI', sector:'S_EMS', themes:['B']},
  {id:'C_MOSCHIP', label:'MosChip Technologies', ticker:'MOSCHIP', sector:'S_EMS', themes:['B']},

  // Theme B - connectivity & cables
  {id:'C_STLTECH', label:'Sterlite Technologies', ticker:'STLTECH', sector:'S_TELECOM', themes:['B']},
  {id:'C_HFCL', label:'HFCL', ticker:'HFCL', sector:'S_TELECOM', themes:['B']},
  {id:'C_TEJASNET', label:'Tejas Networks', ticker:'TEJASNET', sector:'S_TELECOM', themes:['B']},
  {id:'C_INDUSTOWER', label:'Indus Towers', ticker:'INDUSTOWER', sector:'S_TELECOM', themes:['B']},
  {id:'C_POLYCAB', label:'Polycab India', ticker:'POLYCAB', sector:'S_CABLES', themes:['A','B']},
  {id:'C_KEI', label:'KEI Industries', ticker:'KEI', sector:'S_CABLES', themes:['A','B']},
  {id:'C_RRKABEL', label:'R R Kabel', ticker:'RRKABEL', sector:'S_CABLES', themes:['A','B']},
  {id:'C_FINCABLES', label:'Finolex Cables', ticker:'FINCABLES', sector:'S_CABLES', themes:['A','B']},
  {id:'C_RAMRATNA', label:'Ram Ratna Wires', ticker:'RAMRAT', sector:'S_CABLES', themes:['B']},
  {id:'C_PRECWIRE', label:'Precision Wires India', ticker:'PRECWIRE', sector:'S_CABLES', themes:['B']},
  {id:'C_SKIPPER', label:'Skipper', ticker:'SKIPPER', sector:'S_CABLES', themes:['B']},

  // Theme B - EPC
  {id:'C_LT', label:'Larsen & Toubro', ticker:'LT', sector:'S_EPC', themes:['A','B']},
  {id:'C_TECHNOE', label:'Techno Electric & Engineering', ticker:'TECHNOE', sector:'S_EPC', themes:['B']},
  {id:'C_KALPATPOWR', label:'Kalpataru Projects', ticker:'KPIL', sector:'S_EPC', themes:['A','B']},
  {id:'C_KEC', label:'KEC International', ticker:'KEC', sector:'S_EPC', themes:['A','B']},
  {id:'C_AHLUCONT', label:'Ahluwalia Contracts', ticker:'AHLUCONT', sector:'S_EPC', themes:['B']},
  {id:'C_PSPPROJECT', label:'PSP Projects', ticker:'PSPPROJECT', sector:'S_EPC', themes:['B']},
  {id:'C_AFCONS', label:'Afcons Infrastructure', ticker:'AFCONS', sector:'S_EPC', themes:['A']},

  // Theme B - power & storage
  {id:'C_NTPC', label:'NTPC', ticker:'NTPC', sector:'S_POWER', themes:['A','B']},
  {id:'C_NTPCGREEN', label:'NTPC Green Energy', ticker:'NTPCGREEN', sector:'S_POWER', themes:['B']},
  {id:'C_POWERGRID', label:'Power Grid Corporation', ticker:'POWERGRID', sector:'S_POWER', themes:['B']},
  {id:'C_TATAPOWER', label:'Tata Power', ticker:'TATAPOWER', sector:'S_POWER', themes:['B']},
  {id:'C_ADANIPOWER', label:'Adani Power', ticker:'ADANIPOWER', sector:'S_POWER', themes:['B']},
  {id:'C_ADANIGREEN', label:'Adani Green Energy', ticker:'ADANIGREEN', sector:'S_POWER', themes:['B']},
  {id:'C_JSWENERGY', label:'JSW Energy', ticker:'JSWENERGY', sector:'S_POWER', themes:['B']},
  {id:'C_TORNTPOWER', label:'Torrent Power', ticker:'TORNTPOWER', sector:'S_POWER', themes:['A','B']},
  {id:'C_NHPC', label:'NHPC', ticker:'NHPC', sector:'S_POWER', themes:['B']},
  {id:'C_IEX', label:'Indian Energy Exchange', ticker:'IEX', sector:'S_POWER', themes:['B']},
  {id:'C_SUZLON', label:'Suzlon Energy', ticker:'SUZLON', sector:'S_POWER', themes:['B']},
  {id:'C_INOXWIND', label:'Inox Wind', ticker:'INOXWIND', sector:'S_POWER', themes:['B']},
  {id:'C_KPIGREEN', label:'KPI Green Energy', ticker:'KPIGREEN', sector:'S_POWER', themes:['B']},
  {id:'C_WAAREE', label:'Waaree Energies', ticker:'WAAREEENER', sector:'S_POWER', themes:['A','B']},
  {id:'C_PREMIER', label:'Premier Energies', ticker:'PREMIERENE', sector:'S_POWER', themes:['A','B']},
  {id:'C_EXIDE', label:'Exide Industries', ticker:'EXIDEIND', sector:'S_POWER', themes:['B']},
  {id:'C_AMARAJA', label:'Amara Raja Energy & Mobility', ticker:'ARE&M', sector:'S_POWER', themes:['B']},
  {id:'C_SERVOTECH', label:'Servotech Renewable Power', ticker:'SERVOTECH', sector:'S_POWER', themes:['B']},
  {id:'C_PFC', label:'Power Finance Corporation', ticker:'PFC', sector:'S_BFSI', themes:['B']},
  {id:'C_RECLTD', label:'REC Ltd', ticker:'RECLTD', sector:'S_BFSI', themes:['B']},
  {id:'C_IREDA', label:'IREDA', ticker:'IREDA', sector:'S_BFSI', themes:['A','B']},

  // Theme B - water & services
  {id:'C_VATECHWABAG', label:'VA Tech Wabag', ticker:'WABAG', sector:'S_WATER', themes:['B']},
  {id:'C_IONEXCHANGE', label:'Ion Exchange India', ticker:'IONEXCHANG', sector:'S_WATER', themes:['B']},
  {id:'C_TEAMLEASE', label:'TeamLease Services', ticker:'TEAMLEASE', sector:'S_IT', themes:['B']},
  {id:'C_QUESS', label:'Quess Corp', ticker:'QUESS', sector:'S_IT', themes:['B']}
] AS c
MERGE (x:Node {id:c.id})
SET x.type='COMPANY', x.label=c.label, x.ticker=c.ticker, x.themes=c.themes, x.purity=c.purity
WITH c, x
MATCH (s:Node {id:c.sector})
MERGE (s)-[:CONTAINS]->(x);

// ------------------------------------------------------------
// 3. EDGES
// ------------------------------------------------------------
// Each row: {s: source, t: target, r: relationship, o: order, sign, ch: channel}

UNWIND [
  // --- Theme A macro spine ---
  {s:'E_HORMUZ', t:'M_BRENT', r:'CAUSES', sign:'+'},
  {s:'E_HORMUZ', t:'M_LNG_SPOT', r:'CAUSES', sign:'+'},
  {s:'E_HORMUZ', t:'M_LPG_SAUDI_CP', r:'CAUSES', sign:'+'},
  {s:'E_HORMUZ', t:'M_WARRISK', r:'CAUSES', sign:'+', ch:'0.125% -> 2.5-5% of hull value per transit'},
  {s:'E_HORMUZ', t:'M_FREIGHT', r:'CAUSES', sign:'+'},
  {s:'E_HORMUZ', t:'M_GRM', r:'CAUSES', sign:'+'},
  {s:'E_HORMUZ', t:'M_UREA', r:'CAUSES', sign:'+'},
  {s:'M_BRENT', t:'M_CAD', r:'CAUSES', sign:'+', ch:'$10/bbl ~ -0.1 to -0.2pp GDP'},
  {s:'M_CAD', t:'M_INR', r:'CAUSES', sign:'+'},
  {s:'M_BRENT', t:'M_CPI', r:'CAUSES', sign:'+'},
  {s:'M_INR', t:'M_CPI', r:'CAUSES', sign:'+'},
  {s:'M_CPI', t:'M_REPO', r:'CAUSES', sign:'+'},
  {s:'M_UREA', t:'M_SUBSIDY', r:'CAUSES', sign:'+'},
  {s:'M_LPG_SAUDI_CP', t:'M_SUBSIDY', r:'CAUSES', sign:'+'},
  {s:'RM_CRUDE', t:'G_HORMUZ', r:'TRANSITS', ch:'41-53% of India imports'},
  {s:'RM_LNG', t:'G_HORMUZ', r:'TRANSITS', ch:'~55%'},
  {s:'RM_LPG', t:'G_HORMUZ', r:'TRANSITS', ch:'~88-90%'},
  {s:'RM_UREA', t:'G_HORMUZ', r:'TRANSITS', ch:'~70% of imports'},
  {s:'RM_SULPHUR', t:'G_HORMUZ', r:'TRANSITS'},
  {s:'RM_AMMONIA', t:'G_HORMUZ', r:'TRANSITS'},
  {s:'G_INDIA', t:'G_HORMUZ', r:'IMPORTS_VIA'},
  {s:'G_CAPE', t:'G_HORMUZ', r:'SUBSTITUTES_FOR', ch:'+3800nm, +10-14 days'},
  {s:'RM_UREA', t:'G_OMAN', r:'SOURCED_FROM', ch:'largest single supplier'},
  {s:'RM_LNG', t:'G_QATAR', r:'SOURCED_FROM'},
  {s:'RM_SULPHUR', t:'G_GCC', r:'SOURCED_FROM'},

  // --- Theme A first order ---
  {s:'C_ONGC', t:'RM_CRUDE', r:'PRODUCES'},
  {s:'C_ONGC', t:'M_BRENT', r:'BENEFITS_FROM', o:1, ch:'realisation tracks Brent'},
  {s:'C_OIL', t:'M_BRENT', r:'BENEFITS_FROM', o:1},
  {s:'C_ONGC', t:'POL_WINDFALL_TAX', r:'HURT_BY', o:1, ch:'clawback of upstream windfall'},
  {s:'C_ONGC', t:'C_MRPL', r:'OWNS'},
  {s:'C_ONGC', t:'C_HPCL', r:'OWNS', ch:'~51%'},
  {s:'C_GAIL', t:'E_HORMUZ', r:'HEDGES', ch:'transmission volume vs petchem feedstock cost'},
  {s:'C_IOC', t:'RM_CRUDE', r:'NEEDS'},
  {s:'C_IOC', t:'M_LPG_SAUDI_CP', r:'HURT_BY', o:1, ch:'LPG under-recovery'},
  {s:'C_HPCL', t:'M_LPG_SAUDI_CP', r:'HURT_BY', o:1, ch:'largest LPG mix'},
  {s:'C_BPCL', t:'M_LPG_SAUDI_CP', r:'HURT_BY', o:1},
  {s:'C_IOC', t:'M_GRM', r:'BENEFITS_FROM', o:1},
  {s:'C_MRPL', t:'M_GRM', r:'BENEFITS_FROM', o:1, ch:'pure refiner, no marketing drag'},
  {s:'C_CPCL', t:'M_GRM', r:'BENEFITS_FROM', o:1},
  {s:'C_MRPL', t:'E_HORMUZ', r:'HURT_BY', o:1, ch:'Gulf-concentrated crude slate'},
  {s:'C_RIL', t:'E_HORMUZ', r:'HEDGES', ch:'O2C cost vs GRM and gas realisation'},
  {s:'C_IOC', t:'POL_LPG_SUBSIDY', r:'REGULATED_BY'},
  {s:'C_PETRONET', t:'E_HORMUZ', r:'HURT_BY', o:1, ch:'regas throughput on Qatari curtailment'},
  {s:'C_IGL', t:'M_LNG_SPOT', r:'HURT_BY', o:1, ch:'APM shortfall filled with spot'},
  {s:'C_MGL', t:'M_LNG_SPOT', r:'HURT_BY', o:1},
  {s:'C_GUJGAS', t:'M_LNG_SPOT', r:'HURT_BY', o:1, ch:'industrial customers switch away'},
  {s:'C_IGL', t:'M_BRENT', r:'BENEFITS_FROM', o:2, ch:'CNG conversion economics improve'},
  {s:'C_GUJGAS', t:'POL_GAS_CONTROL_ORDER', r:'REGULATED_BY'},
  {s:'C_GESHIP', t:'M_FREIGHT', r:'BENEFITS_FROM', o:1, ch:'tanker day rates'},
  {s:'C_SCI', t:'M_FREIGHT', r:'BENEFITS_FROM', o:1},
  {s:'C_GESHIP', t:'M_WARRISK', r:'HURT_BY', o:1},
  {s:'C_ADANIPORTS', t:'E_HORMUZ', r:'HURT_BY', o:2, ch:'Gulf trade lane volumes'},
  {s:'C_CONCOR', t:'M_FREIGHT', r:'HURT_BY', o:2},
  {s:'C_TCI', t:'M_BRENT', r:'HURT_BY', o:2, ch:'diesel opex'},
  {s:'C_INDIGO', t:'P_ATF', r:'NEEDS'},
  {s:'P_ATF', t:'M_BRENT', r:'PRICE_LINKED_TO', ch:'beta ~1'},
  {s:'C_INDIGO', t:'M_BRENT', r:'HURT_BY', o:1},
  {s:'C_INDIGO', t:'M_INR', r:'HURT_BY', o:2, ch:'USD lease rentals'},
  {s:'C_SPICEJET', t:'M_BRENT', r:'HURT_BY', o:1},
  {s:'RM_COAL', t:'RM_LNG', r:'SUBSTITUTES_FOR'},
  {s:'C_COALINDIA', t:'M_LNG_SPOT', r:'BENEFITS_FROM', o:1, ch:'gas-to-coal switching'},
  {s:'C_NTPC', t:'M_LNG_SPOT', r:'BENEFITS_FROM', o:2},
  {s:'P_ETHANOL', t:'P_PETROL', r:'SUBSTITUTES_FOR'},
  {s:'C_BALRAMPUR', t:'M_BRENT', r:'BENEFITS_FROM', o:2, ch:'ethanol blending economics'},
  {s:'C_PRAJ', t:'E_HORMUZ', r:'BENEFITS_FROM', o:3, ch:'energy security capex'},
  {s:'C_WAAREE', t:'E_HORMUZ', r:'BENEFITS_FROM', o:3, ch:'RE as import substitution'},

  // --- Theme A second order ---
  {s:'RM_NAPHTHA', t:'M_BRENT', r:'PRICE_LINKED_TO', ch:'beta 0.8-1.0'},
  {s:'RM_CBFS', t:'M_BRENT', r:'PRICE_LINKED_TO'},
  {s:'RM_SYNRUBBER', t:'M_BRENT', r:'PRICE_LINKED_TO'},
  {s:'RM_BASEOIL', t:'M_BRENT', r:'PRICE_LINKED_TO'},
  {s:'RM_PVC', t:'M_BRENT', r:'PRICE_LINKED_TO', ch:'weaker beta; Chinese carbide route'},
  {s:'RM_HDPE', t:'RM_NAPHTHA', r:'PRICE_LINKED_TO'},
  {s:'RM_PETCOKE', t:'M_BRENT', r:'PRICE_LINKED_TO'},
  {s:'RM_LLP', t:'M_BRENT', r:'PRICE_LINKED_TO'},
  {s:'P_PAINT', t:'RM_SOLVENT', r:'NEEDS'},
  {s:'P_PAINT', t:'RM_TIO2', r:'NEEDS'},
  {s:'P_PAINT', t:'RM_MONOMER', r:'NEEDS'},
  {s:'C_ASIANPAINT', t:'M_BRENT', r:'HURT_BY', o:2, ch:'pass-through capped by Birla Opus competition'},
  {s:'C_BERGER', t:'M_BRENT', r:'HURT_BY', o:2},
  {s:'C_INDIGOPNT', t:'M_BRENT', r:'HURT_BY', o:2, ch:'weakest pricing power'},
  {s:'C_PIDILITE', t:'RM_VAM', r:'HURT_BY', o:2},
  {s:'P_TYRE', t:'RM_SYNRUBBER', r:'NEEDS'},
  {s:'P_TYRE', t:'RM_CARBONBLACK', r:'NEEDS'},
  {s:'P_TYRE', t:'RM_NATRUBBER', r:'NEEDS'},
  {s:'RM_CARBONBLACK', t:'RM_CBFS', r:'NEEDS'},
  {s:'C_PCBL', t:'M_BRENT', r:'HURT_BY', o:2, ch:'CBFS; formula pricing offsets'},
  {s:'C_MRF', t:'M_BRENT', r:'HURT_BY', o:2, ch:'~40% of RM is natural rubber'},
  {s:'C_BALKRISHNA', t:'M_INR', r:'HEDGES', ch:'export revenue offsets RM inflation'},
  {s:'P_PVC_PIPE', t:'RM_PVC', r:'NEEDS'},
  {s:'C_SUPREME', t:'RM_PVC', r:'HURT_BY', o:2, ch:'volatility > level; destocking risk'},
  {s:'C_FINOLEXIND', t:'RM_PVC', r:'HEDGES', ch:'backward integrated'},
  {s:'C_POLYPLEX', t:'RM_PTA_MEG', r:'HURT_BY', o:2},
  {s:'C_EPL', t:'RM_HDPE', r:'HURT_BY', o:2},
  {s:'C_DEEPAKNTR', t:'RM_BENZENE', r:'HURT_BY', o:2, ch:'Chinese phenol imports cap pass-through'},
  {s:'C_AARTIIND', t:'RM_BENZENE', r:'HURT_BY', o:2},
  {s:'C_TATACHEM', t:'M_LNG_SPOT', r:'HURT_BY', o:2, ch:'soda ash energy intensity'},
  {s:'C_GHCL', t:'M_LNG_SPOT', r:'HURT_BY', o:2},
  {s:'C_SRF', t:'M_BRENT', r:'HURT_BY', o:2},
  {s:'P_UREA', t:'RM_NATGAS', r:'NEEDS'},
  {s:'P_DAP', t:'RM_PHOSACID', r:'NEEDS'},
  {s:'P_DAP', t:'RM_SULPHUR', r:'NEEDS'},
  {s:'P_DAP', t:'RM_AMMONIA', r:'NEEDS'},
  {s:'C_CHAMBAL', t:'M_LNG_SPOT', r:'HURT_BY', o:1, ch:'gas feedstock; working capital'},
  {s:'C_COROMANDEL', t:'E_HORMUZ', r:'HURT_BY', o:1, ch:'sulphur + phos acid + ammonia'},
  {s:'C_PARADEEP', t:'RM_SULPHUR', r:'HURT_BY', o:1},
  {s:'C_DEEPAKFERT', t:'RM_AMMONIA', r:'HEDGES', ch:'captive ammonia'},
  {s:'C_CHAMBAL', t:'POL_NBS_SUBSIDY', r:'REGULATED_BY'},
  {s:'C_COROMANDEL', t:'M_SUBSIDY', r:'HURT_BY', o:3, ch:'subsidy disbursal delay'},
  {s:'P_CEMENT', t:'RM_PETCOKE', r:'NEEDS'},
  {s:'P_CEMENT', t:'P_DIESEL', r:'NEEDS', ch:'~25% of cost is freight'},
  {s:'C_ULTRACEMCO', t:'M_BRENT', r:'HURT_BY', o:2},
  {s:'C_HINDALCO', t:'M_BRENT', r:'HURT_BY', o:2, ch:'CP coke, caustic, power ~35-40% of cost'},
  {s:'C_NALCO', t:'M_BRENT', r:'HEDGES', ch:'LME aluminium also rises'},
  {s:'C_MARICO', t:'RM_LLP', r:'HURT_BY', o:2},
  {s:'C_HUL', t:'M_BRENT', r:'HURT_BY', o:2, ch:'LAB, packaging, freight'},
  {s:'C_CASTROL', t:'RM_BASEOIL', r:'HURT_BY', o:2, ch:'~50% of COGS'},
  {s:'C_GULFOIL', t:'RM_BASEOIL', r:'HURT_BY', o:2},
  {s:'C_HEROMOTOCO', t:'M_BRENT', r:'HURT_BY', o:3, ch:'rural running cost'},
  {s:'C_MARUTI', t:'M_BRENT', r:'HURT_BY', o:2},
  {s:'C_TATAMOTORS', t:'M_BRENT', r:'BENEFITS_FROM', o:3, ch:'EV TCO advantage widens'},
  {s:'C_OLECTRA', t:'M_BRENT', r:'BENEFITS_FROM', o:3},
  {s:'C_MM', t:'M_UREA', r:'HURT_BY', o:3, ch:'farm profitability -> tractor demand'},

  // --- Theme A third order ---
  {s:'C_BAJFINANCE', t:'M_REPO', r:'HURT_BY', o:3, ch:'cost of funds'},
  {s:'C_SHRIRAMFIN', t:'M_BRENT', r:'HURT_BY', o:3, ch:'CV borrower cash flow'},
  {s:'C_CHOLAFIN', t:'M_BRENT', r:'HURT_BY', o:3},
  {s:'C_MUTHOOT', t:'E_HORMUZ', r:'BENEFITS_FROM', o:3, ch:'gold rally lifts AUM'},
  {s:'C_MANAPPURAM', t:'E_HORMUZ', r:'BENEFITS_FROM', o:3},
  {s:'C_TCS', t:'M_INR', r:'BENEFITS_FROM', o:3, ch:'1% INR dep ~ 20-25bps EBIT'},
  {s:'C_INFY', t:'M_INR', r:'BENEFITS_FROM', o:3},
  {s:'C_SUNPHARMA', t:'M_INR', r:'BENEFITS_FROM', o:3},
  {s:'C_DIVIS', t:'M_BRENT', r:'HURT_BY', o:2, ch:'solvent + energy in API'},
  {s:'G_KERALA', t:'G_GCC', r:'EXPOSED_TO_ORDERBOOK', ch:'expatriate employment'},
  {s:'C_FEDERALBNK', t:'E_HORMUZ', r:'HEDGES', ch:'NRI deposit inflow vs Gulf job risk'},
  {s:'C_FEDERALBNK', t:'M_INR', r:'BENEFITS_FROM', o:3, ch:'NRE/FCNR accretion'},
  {s:'C_SIB', t:'M_INR', r:'BENEFITS_FROM', o:3},
  {s:'C_CSBBANK', t:'E_HORMUZ', r:'HURT_BY', o:3, ch:'gold LTV reversal risk'},
  {s:'C_LT', t:'G_GCC', r:'EXPOSED_TO_ORDERBOOK'},
  {s:'C_LT', t:'E_HORMUZ', r:'HEDGES', ch:'GCC capex funding vs award deferral'},
  {s:'C_KEC', t:'G_GCC', r:'EXPOSED_TO_ORDERBOOK'},
  {s:'C_VOLTAS', t:'G_GCC', r:'EXPOSED_TO_ORDERBOOK', ch:'legacy Gulf MEP'},
  {s:'C_BEL', t:'E_HORMUZ', r:'BENEFITS_FROM', o:3, ch:'defence budget priority'},
  {s:'C_COCHINSHIP', t:'E_HORMUZ', r:'BENEFITS_FROM', o:3, ch:'naval orders + ship repair'},
  {s:'C_SOLARINDS', t:'E_HORMUZ', r:'BENEFITS_FROM', o:3},
  {s:'C_GICRE', t:'M_WARRISK', r:'HEDGES', ch:'rate hardening vs claims'},
  {s:'C_NIACL', t:'M_WARRISK', r:'BENEFITS_FROM', o:3},

  // --- Theme B structure ---
  {s:'T_GENAI', t:'E_AIBUILD', r:'CAUSES'},
  {s:'CU_HYPERSCALER', t:'E_AIBUILD', r:'CAUSES'},
  {s:'POL_DC_TAX', t:'E_AIBUILD', r:'ENABLES'},
  {s:'POL_INDIAAI', t:'E_AIBUILD', r:'ENABLES'},
  {s:'E_AIBUILD', t:'CN_POWER', r:'CONSTRAINED_BY', ch:'26.3 GW by FY32'},
  {s:'E_AIBUILD', t:'CN_TRANSMISSION', r:'CONSTRAINED_BY'},
  {s:'E_AIBUILD', t:'CN_GPU', r:'CONSTRAINED_BY'},
  {s:'E_AIBUILD', t:'CN_WATER', r:'CONSTRAINED_BY'},
  {s:'E_AIBUILD', t:'CN_LAND', r:'CONSTRAINED_BY'},
  {s:'T_HIGHDENSITY', t:'T_LIQUIDCOOL', r:'CAUSES'},
  {s:'CN_CRGO', t:'P_TRANSFORMER', r:'CONSTRAINS'},
  {s:'CN_GRIDSTAB', t:'P_GRIDEQUIP', r:'CAUSES'},

  // --- Theme B first order ---
  {s:'C_ADANIENT', t:'PC_ADANICONNEX', r:'JV_WITH'},
  {s:'C_ADANIENT', t:'E_AIBUILD', r:'BENEFITS_FROM', o:1, ch:'2 GW -> 5 GW by 2035'},
  {s:'C_RIL', t:'AS_JAMNAGAR_DC', r:'OWNS'},
  {s:'CU_HYPERSCALER', t:'C_RIL', r:'CUSTOMER_OF', ch:'Meta 168 MW lease'},
  {s:'C_RIL', t:'E_AIBUILD', r:'BENEFITS_FROM', o:1},
  {s:'C_BHARTIARTL', t:'PC_NXTRA', r:'OWNS'},
  {s:'C_TATACOMM', t:'E_AIBUILD', r:'BENEFITS_FROM', o:1},
  {s:'C_ANANTRAJ', t:'E_AIBUILD', r:'BENEFITS_FROM', o:1, ch:'land to DC conversion'},
  {s:'C_LODHA', t:'CN_LAND', r:'BENEFITS_FROM', o:1},
  {s:'IN_BLACKSTONE', t:'PC_NEYSA', r:'INVESTS_IN'},
  {s:'IN_BLACKSTONE', t:'PC_AIRTRUNK', r:'INVESTS_IN'},
  {s:'PC_CTRLS', t:'C_NTPCGREEN', r:'JV_WITH', ch:'~2 GW renewable MoU'},
  {s:'AS_VIZAG_DC', t:'G_ANDHRA', r:'LOCATED_IN'},
  {s:'AS_JAMNAGAR_DC', t:'G_GUJARAT', r:'LOCATED_IN'},
  {s:'P_DATACENTRE', t:'P_TRANSFORMER', r:'NEEDS'},
  {s:'P_DATACENTRE', t:'P_SWITCHGEAR', r:'NEEDS'},
  {s:'P_DATACENTRE', t:'P_UPS', r:'NEEDS'},
  {s:'P_DATACENTRE', t:'P_GENSET', r:'NEEDS'},
  {s:'P_DATACENTRE', t:'P_COOLING', r:'NEEDS'},
  {s:'P_DATACENTRE', t:'P_POWERCABLE', r:'NEEDS'},
  {s:'P_DATACENTRE', t:'P_FIBRE', r:'NEEDS'},
  {s:'P_DATACENTRE', t:'P_FIRMPOWER', r:'NEEDS', ch:'~50% of opex'},
  {s:'C_HITACHIENER', t:'P_DATACENTRE', r:'SUPPLIES_TO', ch:'HV transformers, grid connection'},
  {s:'C_ABB', t:'P_DATACENTRE', r:'SUPPLIES_TO', ch:'switchgear, drives, motors'},
  {s:'C_SIEMENS', t:'P_DATACENTRE', r:'SUPPLIES_TO'},
  {s:'C_SIEMENSENER', t:'P_DATACENTRE', r:'SUPPLIES_TO'},
  {s:'C_GEVERNOVA', t:'P_DATACENTRE', r:'SUPPLIES_TO'},
  {s:'C_SCHNEIDER', t:'P_DATACENTRE', r:'SUPPLIES_TO', ch:'UPS, MV/LV, power skids'},
  {s:'C_CGPOWER', t:'P_DATACENTRE', r:'SUPPLIES_TO'},
  {s:'C_VOLTAMP', t:'P_DATACENTRE', r:'SUPPLIES_TO'},
  {s:'C_TRIL', t:'P_DATACENTRE', r:'SUPPLIES_TO'},
  {s:'C_SHILCHAR', t:'P_DATACENTRE', r:'SUPPLIES_TO'},
  {s:'C_CUMMINSIND', t:'P_DATACENTRE', r:'SUPPLIES_TO', ch:'HHP gensets N+1'},
  {s:'C_KOEL', t:'P_DATACENTRE', r:'SUPPLIES_TO'},
  {s:'C_APARINDS', t:'P_TRANSFORMER', r:'SUPPLIES_TO', ch:'transformer oil'},
  {s:'C_TRIL', t:'CN_CRGO', r:'CONSTRAINED_BY'},
  {s:'C_VOLTAMP', t:'CN_CRGO', r:'CONSTRAINED_BY'},
  {s:'T_LIQUIDCOOL', t:'P_COOLING', r:'CAUSES'},
  {s:'C_KRN', t:'C_SCHNEIDER', r:'SUPPLIES_TO', ch:'heat exchangers; targeting ~50% India DC share'},
  {s:'C_BLUESTARCO', t:'P_DATACENTRE', r:'SUPPLIES_TO', ch:'precision AC + MEP/EPC'},
  {s:'C_VOLTAS', t:'P_DATACENTRE', r:'SUPPLIES_TO', ch:'chillers'},
  {s:'C_THERMAX', t:'P_DATACENTRE', r:'SUPPLIES_TO', ch:'chillers, water, captive power'},
  {s:'C_AMBER', t:'P_COOLING', r:'SUPPLIES_TO'},
  {s:'C_JCHAC', t:'P_COOLING', r:'SUPPLIES_TO'},
  {s:'P_AISERVER', t:'RM_GPU', r:'NEEDS'},
  {s:'P_AISERVER', t:'CN_HBM', r:'NEEDS'},
  {s:'C_NETWEB', t:'P_AISERVER', r:'PRODUCES'},
  {s:'C_NETWEB', t:'CU_INDIAAI', r:'SUPPLIES_TO', ch:'Rs 1734cr Blackwell order, Q4FY26-H1FY27'},
  {s:'C_NETWEB', t:'CN_GPU', r:'CONSTRAINED_BY'},
  {s:'PC_NVIDIA', t:'C_NETWEB', r:'SUPPLIES_TO'},
  {s:'C_DIXON', t:'POL_PLI_IT', r:'BENEFITS_FROM', o:1},
  {s:'C_KAYNES', t:'POL_SEMICON', r:'BENEFITS_FROM', o:1},
  {s:'C_CGPOWER', t:'POL_SEMICON', r:'BENEFITS_FROM', o:1},
  {s:'C_STLTECH', t:'P_DATACENTRE', r:'SUPPLIES_TO', ch:'optical fibre'},
  {s:'C_HFCL', t:'P_FIBRE', r:'SUPPLIES_TO'},
  {s:'C_TEJASNET', t:'P_DATACENTRE', r:'SUPPLIES_TO'},
  {s:'C_TATACOMM', t:'CU_HYPERSCALER', r:'SUPPLIES_TO', ch:'subsea + interconnect'},
  {s:'C_POLYCAB', t:'P_DATACENTRE', r:'SUPPLIES_TO'},
  {s:'C_KEI', t:'P_DATACENTRE', r:'SUPPLIES_TO', ch:'HT/EHV cables'},
  {s:'P_POWERCABLE', t:'RM_COPPER', r:'NEEDS'},
  {s:'P_POWERCABLE', t:'RM_PVC', r:'NEEDS'},
  {s:'C_LT', t:'P_DATACENTRE', r:'SUPPLIES_TO', ch:'turnkey shell + MEP + substation'},
  {s:'C_TECHNOE', t:'E_AIBUILD', r:'BENEFITS_FROM', o:1, ch:'substation EPC + own DC'},
  {s:'C_KEC', t:'CN_TRANSMISSION', r:'SUPPLIES_TO'},
  {s:'C_KALPATPOWR', t:'CN_TRANSMISSION', r:'SUPPLIES_TO'},
  {s:'C_SKIPPER', t:'CN_TRANSMISSION', r:'SUPPLIES_TO'},
  {s:'C_POWERGRID', t:'CN_TRANSMISSION', r:'BENEFITS_FROM', o:1, ch:'Rs 9.16 lakh crore plan'},
  {s:'C_NTPCGREEN', t:'PC_CTRLS', r:'SUPPLIES_TO'},
  {s:'C_TATAPOWER', t:'E_AIBUILD', r:'BENEFITS_FROM', o:1, ch:'RTC RE + Mumbai distribution'},
  {s:'C_ADANIGREEN', t:'E_AIBUILD', r:'BENEFITS_FROM', o:1},
  {s:'C_NHPC', t:'CN_GRIDSTAB', r:'BENEFITS_FROM', o:2, ch:'hydro peaking for load ramps'},
  {s:'C_IEX', t:'E_AIBUILD', r:'BENEFITS_FROM', o:2},
  {s:'C_EMBASSY', t:'CU_GCC_ENT', r:'BENEFITS_FROM', o:3},

  // --- Theme B second order ---
  {s:'C_HINDALCO', t:'P_TRANSFORMER', r:'SUPPLIES_TO', ch:'aluminium + copper'},
  {s:'C_HINDCOPPER', t:'RM_COPPER', r:'SUPPLIES_TO'},
  {s:'C_NALCO', t:'RM_ALUMINIUM', r:'SUPPLIES_TO'},
  {s:'C_RAMRATNA', t:'P_TRANSFORMER', r:'SUPPLIES_TO', ch:'winding wire'},
  {s:'C_PRECWIRE', t:'P_TRANSFORMER', r:'SUPPLIES_TO', ch:'enamelled copper wire'},
  {s:'CN_CRGO', t:'C_VOLTAMP', r:'CONSTRAINS'},
  {s:'P_CHILLER', t:'RM_REFRIGERANT', r:'NEEDS'},
  {s:'C_GFL', t:'P_CHILLER', r:'SUPPLIES_TO', ch:'refrigerants, immersion fluid optionality'},
  {s:'C_SRF', t:'P_CHILLER', r:'SUPPLIES_TO'},
  {s:'T_LIQUIDCOOL', t:'RM_REFRIGERANT', r:'CAUSES'},
  {s:'CN_GRIDSTAB', t:'C_EXIDE', r:'CAUSES', ch:'BESS demand'},
  {s:'CN_GRIDSTAB', t:'C_HITACHIENER', r:'CAUSES', ch:'STATCOM, synchronous condensers'},
  {s:'CN_GRIDSTAB', t:'C_AMARAJA', r:'CAUSES'},
  {s:'P_UPS', t:'RM_BATTERY', r:'NEEDS'},
  {s:'C_HBLENGINE', t:'P_UPS', r:'SUPPLIES_TO'},
  {s:'CN_WATER', t:'C_VATECHWABAG', r:'CAUSES', ch:'ZLD + recycling demand'},
  {s:'C_IONEXCHANGE', t:'P_DATACENTRE', r:'SUPPLIES_TO', ch:'DM water, cooling chemistry'},
  {s:'C_ULTRACEMCO', t:'P_DATACENTRE', r:'SUPPLIES_TO'},
  {s:'C_JSWSTEEL', t:'P_DATACENTRE', r:'SUPPLIES_TO'},

  // --- Theme B third order ---
  {s:'C_PFC', t:'CN_POWER', r:'BENEFITS_FROM', o:3},
  {s:'C_RECLTD', t:'CN_POWER', r:'BENEFITS_FROM', o:3},
  {s:'C_IREDA', t:'CN_GRIDSTAB', r:'BENEFITS_FROM', o:3},
  {s:'C_SBIN', t:'E_AIBUILD', r:'BENEFITS_FROM', o:3},
  {s:'C_TEAMLEASE', t:'CN_SKILLS', r:'BENEFITS_FROM', o:3},
  {s:'C_QUESS', t:'CN_SKILLS', r:'BENEFITS_FROM', o:3},
  {s:'C_TCS', t:'T_GENAI', r:'HEDGES', ch:'TAM expansion vs linear model deflation'},
  {s:'C_INFY', t:'T_GENAI', r:'HEDGES'},
  {s:'C_QUICKHEAL', t:'POL_DC_TAX', r:'BENEFITS_FROM', o:3, ch:'DPDP + localisation'},
  {s:'C_INDUSTOWER', t:'T_GENAI', r:'BENEFITS_FROM', o:3, ch:'edge inference'},
  {s:'C_ADANIPORTS', t:'E_AIBUILD', r:'BENEFITS_FROM', o:3, ch:'equipment import volumes'},
  {s:'C_INDIGO', t:'E_AIBUILD', r:'BENEFITS_FROM', o:3, ch:'air-freighted GPU cargo'},
  {s:'C_ANANTRAJ', t:'CN_LAND', r:'BENEFITS_FROM', o:3},
  {s:'C_COALINDIA', t:'CN_POWER', r:'BENEFITS_FROM', o:3, ch:'DC load partly met by coal'},

  // --- Cross-theme mechanism edges ---
  {s:'E_HORMUZ', t:'E_AIBUILD', r:'HURT_BY', o:2, ch:'LNG/power cost -> DC opex (power ~50% of opex)'},
  {s:'M_WARRISK', t:'E_AIBUILD', r:'HURT_BY', o:2, ch:'freight + war risk on imported transformers, chillers, GPUs'},
  {s:'M_INR', t:'C_NETWEB', r:'HURT_BY', o:3, ch:'USD-denominated GPU landed cost'},
  {s:'M_REPO', t:'C_ADANIGREEN', r:'HURT_BY', o:3, ch:'long-duration project WACC'},
  {s:'M_REPO', t:'C_ANANTRAJ', r:'HURT_BY', o:3, ch:'DC project financing cost'}
] AS e

MATCH (a:Node {id: e.s})
MATCH (b:Node {id: e.t})

CREATE (a)-[rel:$(e.r)]->(b)

SET rel.order = e.o,
    rel.sign = e.sign,
    rel.channel = e.ch

RETURN count(rel) AS edges_created;
// NOTE: the final block requires APOC. Without APOC, replace with explicit
// MERGE (a)-[:CAUSES {..}]->(b) statements grouped by relationship type.

// ------------------------------------------------------------
// 4. SAMPLE QUERIES
// ------------------------------------------------------------
// Cross-theme companies:
//   MATCH (c:Node {type:'COMPANY'}) WHERE 'A' IN c.themes AND 'B' IN c.themes RETURN c.label, c.ticker;
//
// All 2nd-order Hormuz losers:
//   MATCH (c:Node {type:'COMPANY'})-[r:HURT_BY]->(m) WHERE r.order = 2 RETURN c.label, type(r), m.label, r.channel;
//
// Shortest causal path from the shock to any company:
//   MATCH p = shortestPath((:Node {id:'E_HORMUZ'})-[*..4]-(c:Node {ticker:'MRF'})) RETURN p;
//
// Bottleneck suppliers in Theme B:
//   MATCH (:Node {id:'E_AIBUILD'})-[:CONSTRAINED_BY]->(cn)<-[]-(c:Node {type:'COMPANY'}) RETURN cn.label, collect(c.ticker);
